### ISSUE TITLE
Could not install package since 2.0-37

### ISSUE THREAD

**Issue by lekoOwO** [T-REX-XP/RRManager#42]
The RR Manager installs normally before 2.0-37, since 2.0-37 (Includes 2.0-37) the package installation failed.

Is there any critical change since 2.0-37?

**Comment by niko44** [comment]
+1 same pb, impossible to update from [v.2.0.19] to [v.2.0.64]... no log

**Comment by Spelvi** [comment]
This happens because you have WEB-STATION installed, it is not compatible with RRManager, uninstall webstation and you will be able to install RRManager, I reported the compatibility error a few days ago in case they can fix it but it seems that the developer of the APP does not come around here much.

**Comment by T-REX-XP** [comment]
Thank you for the detailed feedback. I will take a look on the issue soon.

**Comment by T-REX-XP** [comment]
Fixed conflict with WebStation in the latest release - [v.2.0.74](https://github.com/T-REX-XP/RRManager/releases/tag/v.2.0.74)
