### ISSUE TITLE
这个文件里这句话对么？

### ISSUE THREAD

**Issue by sumingyd** [T-REX-XP/RRManager#54]
INSERT INTO task VALUES('RunRrUpdate', '', 'bootup', '', 0, 0, 0, 0, '', 0, '. /var/packages/rr-manager/ta
这里的  . /var

**Comment by sumingyd** [comment]
我安装上之后  每次打开他都会提示缺少任务，然后点击确定输入密码，计划任务里并没有新增任务。

**Comment by T-REX-XP** [comment]
It's expected behavior. Every time you install the new version of the RRM, you will get that prompt to enter the password. RRM will clear up all the temporary tasks after applying it. This logic was implemented to ensure that garbage will be cleared automatically and all required steps will be applied after the reinstall of RRM.
